### PR TITLE
Port Styx's latest code to AC

### PR DESCRIPTION
**Pull request by gtao725**
All improvements and bug fixes to date from Styx are included.

### CODE REVIEW

**Comment by milestorme** [comment]
tested and working on AC>AzerothCore rev. a0cb2c0b7c66+ 2019-04-13 16:09:19 +0000 (master branch) (Unix, Release)

**Review by FrancescoBorzi — APPROVED** [review]

**Comment by gtao725** [comment]
Just tested again, all good, can merge I believe.

**Comment by milestorme** [comment]
tested and working finally thank you ,AC>AzerothCore rev. a0cb2c0b7c66+ 2019-04-13 16:09:19 +0000 (master branch) (Unix, Release)

**Comment by milestorme** [comment]
This one is working very well now

**Comment by gtao725** [comment]
Thx. Can definitely merge.

**Comment by FrancescoBorzi** [comment]
good job @gtao725 and @milestorme

**Comment by BarbzYHOOL** [comment]
@gtao725 @milestorme thank you

**Pull request merged**
