### PR TITLE
merge

### PR DESCRIPTION
**Pull request by BarbzYHOOL**
A few fixes to travis and git files, and some maybe unwanted changes to the CPP, please review it

### CODE REVIEW

**Comment by FrancescoBorzi** [comment]
> and some maybe unwanted changes to the CPP

@BarbzYHOOL what do you mean with that?

**Comment by BarbzYHOOL** [comment]
at the end of the diff there are changes but I didn't review
There were changes to the values for wtf reason

**Comment by Helias** [comment]
What about to merge/close? @BarbzYHOOL

**Comment by BarbzYHOOL** [comment]
merge conflict, no time atm

if you can fix it


btw since no more travis in core, how does it affect all modules??

**Comment by Helias** [comment]
I think that we can't update this PR, because the branch is deleted.

image

**Comment by BarbzYHOOL** [comment]
it was on micrah's repo (so not my work in fact xD)

well you can git pull that PR then you close this PR, you fix the conflict and then you make a new PR

**Pull request closed without merging**
