### PR TITLE
fixed typo

### PR DESCRIPTION
**Pull request by milestorme**
Build error Linux , typo in gambler.cpp , fixed

### CODE REVIEW

**Comment by milestorme** [comment]
hope I have done the pr as you asked, I'm a little rusty with the git

**Comment by BarbzYHOOL** [comment]
yes, correctly done (but if you have to do something more complex using command line it's different though :P)

**Comment by BarbzYHOOL** [comment]
@milestorme thank you!

**Comment by FrancescoBorzi** [comment]
good job @milestorme

**Pull request merged**
